//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApp1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] AngleSharp {
            get {
                object obj = ResourceManager.GetObject("AngleSharp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;AngleSharp&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:AngleSharp.Attributes.Accessors&quot;&gt;
        ///            &lt;summary&gt;
        ///            The various DOM object accessor types.
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;F:AngleSharp.Attributes.Accessors.None&quot;&gt;
        ///            &lt;summary&gt;
        ///            Specifies that the property does not have any special meaning.
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member na [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string AngleSharp1 {
            get {
                return ResourceManager.GetString("AngleSharp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CrewingCompanies1_1_01 {
            get {
                object obj = ResourceManager.GetObject("CrewingCompanies1_1_01", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] EntityFramework {
            get {
                object obj = ResourceManager.GetObject("EntityFramework", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] EntityFramework_SqlServer {
            get {
                object obj = ResourceManager.GetObject("EntityFramework_SqlServer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;EntityFramework.SqlServer&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:System.Data.Entity.SqlServer.SqlAzureExecutionStrategy&quot;&gt;
        ///            &lt;summary&gt;
        ///            An &lt;see cref=&quot;T:System.Data.Entity.Infrastructure.IDbExecutionStrategy&quot;/&gt; that retries actions that throw exceptions caused by SQL Azure transient failures.
        ///            &lt;/summary&gt;
        ///            &lt;remarks&gt;
        ///            This execution strategy will retry the operation on  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string EntityFramework_SqlServer1 {
            get {
                return ResourceManager.GetString("EntityFramework_SqlServer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;EntityFramework&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:System.Data.Entity.Core.Common.CommandTrees.BasicCommandTreeVisitor&quot;&gt;
        ///            &lt;summary&gt;
        ///            An abstract base type for types that implement the IExpressionVisitor interface to derive from.
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;M:System.Data.Entity.Core.Common.CommandTrees.BasicCommandTreeVisitor.VisitSetClause(System.Data.Entity. [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string EntityFramework1 {
            get {
                return ResourceManager.GetString("EntityFramework1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] MaterialDesignColors {
            get {
                object obj = ResourceManager.GetObject("MaterialDesignColors", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] MaterialDesignColors1 {
            get {
                object obj = ResourceManager.GetObject("MaterialDesignColors1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] MaterialDesignThemes_Wpf {
            get {
                object obj = ResourceManager.GetObject("MaterialDesignThemes_Wpf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] MaterialDesignThemes_Wpf1 {
            get {
                object obj = ResourceManager.GetObject("MaterialDesignThemes_Wpf1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;MaterialDesignThemes.Wpf&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:MaterialDesignThemes.Wpf.ButtonAssist&quot;&gt;
        ///            &lt;summary&gt;
        ///            Helper properties for working with for make round corner.
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;F:MaterialDesignThemes.Wpf.ButtonAssist.CornerRadiusProperty&quot;&gt;
        ///            &lt;summary&gt;
        ///            Controls the corner radius of the surrounding box.
        ///             [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string MaterialDesignThemes_Wpf2 {
            get {
                return ResourceManager.GetString("MaterialDesignThemes_Wpf2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_Data_Sqlite {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Data_Sqlite", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;Microsoft.Data.Sqlite&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;M:Microsoft.Data.Sqlite.Properties.Resources.CallRequiresOpenConnection(System.Object)&quot;&gt;
        ///            &lt;summary&gt;
        ///            {methodName} can only be called when the connection is open.
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;M:Microsoft.Data.Sqlite.Properties.Resources.CallRequiresSetCommandText(System.Object)&quot;&gt;
        ///            &lt;summary&gt;
        ///    [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Microsoft_Data_Sqlite1 {
            get {
                return ResourceManager.GetString("Microsoft_Data_Sqlite1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SQLitePCLRaw_batteries_v2 {
            get {
                object obj = ResourceManager.GetObject("SQLitePCLRaw_batteries_v2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SQLitePCLRaw_core {
            get {
                object obj = ResourceManager.GetObject("SQLitePCLRaw_core", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SQLitePCLRaw_nativelibrary {
            get {
                object obj = ResourceManager.GetObject("SQLitePCLRaw_nativelibrary", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SQLitePCLRaw_provider_dynamic_cdecl {
            get {
                object obj = ResourceManager.GetObject("SQLitePCLRaw_provider_dynamic_cdecl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] System_Buffers {
            get {
                object obj = ResourceManager.GetObject("System_Buffers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;span&gt;
        ///&lt;doc&gt;
        ///  &lt;assembly&gt;
        ///    &lt;name&gt;System.Buffers&lt;/name&gt;
        ///  &lt;/assembly&gt;
        ///  &lt;members&gt;
        ///    &lt;member name=&quot;T:System.Buffers.ArrayPool`1&quot;&gt;
        ///      &lt;summary&gt;Provides a resource pool that enables reusing instances of type &lt;see cref=&quot;T[]&quot;&gt;&lt;/see&gt;.&lt;/summary&gt;
        ///      &lt;typeparam name=&quot;T&quot;&gt;The type of the objects that are in the resource pool.&lt;/typeparam&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;M:System.Buffers.ArrayPool`1.#ctor&quot;&gt;
        ///      &lt;summary&gt;Initializes a new instance of the &lt;see c [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string System_Buffers1 {
            get {
                return ResourceManager.GetString("System_Buffers1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] System_Data_SQLite {
            get {
                object obj = ResourceManager.GetObject("System_Data_SQLite", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!--
        /// *
        /// * System.Data.SQLite.dll.config -
        /// *
        /// * WARNING: This XML configuration file is intended for use within the NuGet
        /// *          package directories only.  Please do not copy this file to any of
        /// *          the build output directories because it could interfere with the
        /// *          native library pre-loading feature.
        /// *
        /// * Written by Joe Mistachkin.
        /// * Released to the public domain, use at your own risk!
        /// *
        ///--&gt;
        ///&lt;configuration&gt;
        ///  &lt;appSettings&gt;
        ///    &lt;add key=&quot;PreLoa [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string System_Data_SQLite_dll {
            get {
                return ResourceManager.GetString("System_Data_SQLite_dll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] System_Data_SQLite_EF6 {
            get {
                object obj = ResourceManager.GetObject("System_Data_SQLite_EF6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] System_Data_SQLite_Linq {
            get {
                object obj = ResourceManager.GetObject("System_Data_SQLite_Linq", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;System.Data.SQLite&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:System.Data.SQLite.AssemblySourceIdAttribute&quot;&gt;
        ///            &lt;summary&gt;
        ///            Defines a source code identifier custom attribute for an assembly
        ///            manifest.
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;M:System.Data.SQLite.AssemblySourceIdAttribute.#ctor(System.String)&quot;&gt;
        ///            &lt;summary&gt;
        ///            Constructs an instance of [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string System_Data_SQLite1 {
            get {
                return ResourceManager.GetString("System_Data_SQLite1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] System_Memory {
            get {
                object obj = ResourceManager.GetObject("System_Memory", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;doc&gt;
        ///  &lt;assembly&gt;
        ///    &lt;name&gt;System.Memory&lt;/name&gt;
        ///  &lt;/assembly&gt;
        ///  &lt;members&gt;
        ///    &lt;member name=&quot;T:System.Span`1&quot;&gt;
        ///      &lt;typeparam name=&quot;T&quot;&gt;&lt;/typeparam&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;M:System.Span`1.#ctor(`0[])&quot;&gt;
        ///      &lt;param name=&quot;array&quot;&gt;&lt;/param&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;M:System.Span`1.#ctor(System.Void*,System.Int32)&quot;&gt;
        ///      &lt;param name=&quot;pointer&quot;&gt;&lt;/param&gt;
        ///      &lt;param name=&quot;length&quot;&gt;&lt;/param&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;M:System.Span`1.#ctor(` [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string System_Memory1 {
            get {
                return ResourceManager.GetString("System_Memory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] System_Numerics_Vectors {
            get {
                object obj = ResourceManager.GetObject("System_Numerics_Vectors", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;span&gt;
        ///&lt;doc&gt;
        ///  &lt;assembly&gt;
        ///    &lt;name&gt;System.Numerics.Vectors&lt;/name&gt;
        ///  &lt;/assembly&gt;
        ///  &lt;members&gt;
        ///    &lt;member name=&quot;T:System.Numerics.Matrix3x2&quot;&gt;
        ///      &lt;summary&gt;Represents a 3x2 matrix.&lt;/summary&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;M:System.Numerics.Matrix3x2.#ctor(System.Single,System.Single,System.Single,System.Single,System.Single,System.Single)&quot;&gt;
        ///      &lt;summary&gt;Creates a 3x2 matrix from the specified components.&lt;/summary&gt;
        ///      &lt;param name=&quot;m11&quot;&gt;The value to assig [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string System_Numerics_Vectors1 {
            get {
                return ResourceManager.GetString("System_Numerics_Vectors1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] System_Runtime_CompilerServices_Unsafe {
            get {
                object obj = ResourceManager.GetObject("System_Runtime_CompilerServices_Unsafe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;doc&gt;
        ///  &lt;assembly&gt;
        ///    &lt;name&gt;System.Runtime.CompilerServices.Unsafe&lt;/name&gt;
        ///  &lt;/assembly&gt;
        ///  &lt;members&gt;
        ///    &lt;member name=&quot;T:System.Runtime.CompilerServices.Unsafe&quot;&gt;
        ///      &lt;summary&gt;Contains generic, low-level functionality for manipulating pointers.&lt;/summary&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;M:System.Runtime.CompilerServices.Unsafe.Add``1(``0@,System.Int32)&quot;&gt;
        ///      &lt;summary&gt;Adds an element offset to the given reference.&lt;/summary&gt;
        ///      &lt;param name=&quot;source&quot;&gt;The refe [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string System_Runtime_CompilerServices_Unsafe1 {
            get {
                return ResourceManager.GetString("System_Runtime_CompilerServices_Unsafe1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] System_Text_Encoding_CodePages {
            get {
                object obj = ResourceManager.GetObject("System_Text_Encoding_CodePages", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] WhatsAppApi {
            get {
                object obj = ResourceManager.GetObject("WhatsAppApi", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
